"""Generate annotated screenshots of every Spectro workflow on the demo project.

Each screenshot gets a banner stating the workflow and the benefit, and an
``index.html`` gallery plus ``README.md`` are written next to the images.

    python tools/workflow_screenshots.py                 # → docs/workflows/
    python tools/workflow_screenshots.py --out shots --only optimizer,import

Runs headless when no display is available (Qt "offscreen" platform).
"""

from __future__ import annotations

import argparse
import html
import os
import sys
import tempfile
import traceback
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
sys.path.insert(0, str(Path(__file__).resolve().parent))
if not os.environ.get("DISPLAY") and sys.platform.startswith("linux"):
    os.environ.setdefault("QT_QPA_PLATFORM", "offscreen")

import numpy as np  # noqa: E402
from _png import compact_png  # noqa: E402
from PySide6.QtCore import QRect, Qt  # noqa: E402
from PySide6.QtGui import QColor, QFont, QPainter, QPixmap  # noqa: E402
from PySide6.QtWidgets import QApplication, QMessageBox, QTextBrowser  # noqa: E402

BANNER_BG, TITLE, BODY, ACCENT = "#f0efec", "#0b0b0b", "#52514e", "#2a78d6"


class Shooter:
    def __init__(self, out: Path, app: QApplication):
        self.out, self.app = out, app
        self.entries: list[dict] = []
        out.mkdir(parents=True, exist_ok=True)

    def shot(self, widget, key: str, title: str, benefit: str, steps: str = "") -> None:
        widget.show()
        for _ in range(3):
            self.app.processEvents()
        pm = widget.grab()
        banner_h = 92
        full = QPixmap(pm.width(), pm.height() + banner_h)
        full.fill(QColor(BANNER_BG))
        p = QPainter(full)
        p.fillRect(QRect(0, 0, 6, banner_h), QColor(ACCENT))
        f = QFont()
        f.setPointSize(15)
        f.setBold(True)
        p.setFont(f)
        p.setPen(QColor(TITLE))
        n = len(self.entries) + 1
        p.drawText(QRect(22, 8, pm.width() - 40, 30), Qt.AlignLeft | Qt.AlignVCenter,
                   f"{n}. {title}")
        f.setPointSize(10)
        f.setBold(False)
        p.setFont(f)
        p.setPen(QColor(BODY))
        p.drawText(QRect(22, 40, pm.width() - 40, 50), Qt.AlignLeft | Qt.TextWordWrap,
                   f"Benefit: {benefit}" + (f"   ·   How: {steps}" if steps else ""))
        p.drawPixmap(0, banner_h, pm)
        p.end()
        name = f"{n:02d}_{key}.png"
        full.save(str(self.out / name))
        compact_png(self.out / name)
        self.entries.append({"file": name, "title": title, "benefit": benefit, "steps": steps})
        print(f"  saved {name}")

    def write_index(self) -> None:
        cards = "\n".join(
            f"<figure><img src='{e['file']}' alt='{html.escape(e['title'])}'>"
            f"<figcaption><b>{i}. {html.escape(e['title'])}</b><br>"
            f"<span>{html.escape(e['benefit'])}</span>"
            + (f"<br><i>How: {html.escape(e['steps'])}</i>" if e["steps"] else "")
            + "</figcaption></figure>" for i, e in enumerate(self.entries, 1))
        (self.out / "index.html").write_text(f"""<!doctype html><html><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1"><title>Spectro workflows</title>
<style>body{{font-family:Segoe UI,Arial,sans-serif;margin:24px;background:#fcfcfb;color:#0b0b0b}}
h1{{margin:0 0 4px}} p.lead{{color:#52514e;max-width:900px}}
figure{{margin:28px 0;border:1px solid #e3e2de;border-radius:8px;overflow:hidden;background:#fff}}
img{{width:100%;display:block}} figcaption{{padding:10px 14px;color:#52514e}}
figcaption b{{color:#0b0b0b}}</style></head><body>
<h1>Spectro — workflows</h1><p class="lead">Screenshots generated automatically by
<code>tools/workflow_screenshots.py</code> on the bundled demo project (paracetamol / caffeine /
aspirin; simulated spectra with realistic noise). How to apply each individual method is in the
<a href="../methods/index.html">method guide</a>.</p>{cards}</body></html>""", encoding="utf-8")
        md = ["# Spectro — workflows", "",
              "Generated by `python tools/workflow_screenshots.py` on the demo project "
              "(simulated spectra with realistic noise). How to apply each individual method is "
              "in the [method guide](../methods/README.md).", ""]
        for i, e in enumerate(self.entries, 1):
            md += [f"## {i}. {e['title']}", "", f"**Benefit:** {e['benefit']}", ""]
            if e["steps"]:
                md += [f"*How:* {e['steps']}", ""]
            md += [f"![{e['title']}]({e['file']})", ""]
        (self.out / "README.md").write_text("\n".join(md), encoding="utf-8")


# --------------------------------------------------------------------------- #
# Workflows
# --------------------------------------------------------------------------- #
def select(win, ids):
    win.tree.clearSelection()
    stack = [win.tree.invisibleRootItem()]
    while stack:
        node = stack.pop()
        for i in range(node.childCount()):
            ch = node.child(i)
            if ch.data(0, Qt.UserRole) in ids:
                ch.setSelected(True)
            stack.append(ch)


def check_only(lst, ids):
    for i in range(lst.count()):
        it = lst.item(i)
        it.setCheckState(Qt.Checked if it.data(Qt.UserRole) in ids else Qt.Unchecked)


class Demo:
    def __init__(self, shooter: Shooter, workdir: Path):
        import spectro.ui.dialogs_data as dd
        import spectro.ui.main_window as mw
        import spectro.ui.widgets as w
        from spectro.demo import build_demo_project

        for mod in (w, dd, mw):  # no interactive prompts
            setattr(mod, "ask_reason", lambda *a, **k: "workflow demo")
        QMessageBox.information = staticmethod(lambda *a, **k: None)
        QMessageBox.question = staticmethod(lambda *a, **k: QMessageBox.Yes)
        self.s = shooter
        self.win = mw.MainWindow()
        self.win.resize(1500, 900)
        self.win.show()
        self.win._attach(build_demo_project(workdir / "demo.spectro"))
        self.p = self.win.project
        self.recs = self.p.records()

    def ids(self, pred):
        return [r.id for r in self.p.records() if pred(r)]

    def named(self, name):
        return next(r.id for r in self.p.records() if r.name == name)

    # 1
    def import_any_instrument(self):
        from spectro.demo import data_dir
        from spectro.ui.dialogs_data import ImportDialog
        d = ImportDialog(self.win)
        base = data_dir()
        d.files = [str(base / f) for f in (
            "binary/shimadzu_txt/PAR_10.txt", "binary/CAF_standards_xy_pairs.csv",
            "binary/lab_mixtures.xlsx", "binary/panadol_extra_tablets.csv",
            "ternary/training_set_brereton.jdx", "ternary/validation_mixtures.tsv",
            "ternary/excedrin_tablets.spc")]
        d._reparse()
        d._parse_names()
        d.table.selectRow(12)
        self.s.shot(d, "import", "Import from any instrument, Excel or CSV",
                    "one dialog reads text/CSV (any delimiter, decimal comma), Excel, JCAMP-DX "
                    "and SPC exports; layout and names are detected and concentrations are "
                    "filled from sample names — no manual re-typing.",
                    "File → Import spectra…")

    # 2
    def organize(self):
        select(self.win, self.ids(lambda r: r.kind == "raw" and r.role in ("standard", "divisor")
                                  and r.name.startswith("PAR")))
        self.s.shot(self.win, "project", "Organize trials, standards, mixtures and samples",
                    "every spectrum lives in one project file with its trial, role and "
                    "concentrations; selecting spectra plots them instantly with a λ/A readout.",
                    "Project tree + plot")
        tab = self.named("Panadol Extra tablet 1 (label claim)")
        select(self.win, [tab])
        self.win.props.setCurrentIndex(3)
        self.s.shot(self.win, "history", "Every operation logged per spectrum",
                    "the History tab lists each import, edit, processing step and calculation "
                    "that touched this spectrum, with user, time and reason.",
                    "Select a spectrum → History tab")
        self.win.props.setCurrentIndex(0)

    # 3
    def audit(self):
        from spectro.ui.dialogs_data import AuditDialog
        d = AuditDialog(self.win)
        d.resize(1400, 780)
        row = next(i for i, e in enumerate(d.entries) if e.action == "PROCESS")
        d.table.selectRow(row)
        self.s.shot(d, "audit", "Tamper-evident audit trail",
                    "append-only, hash-chained log (ALCOA+ / Part 11 style): full parameters, "
                    "input/output data hashes and before/after values; any tampering is "
                    "detected by Verify integrity.", "Audit → Audit trail")

    # 4
    def pipeline(self):
        from spectro.ui.dialogs_data import ProcessDialog
        mixes = self.ids(lambda r: r.kind == "raw" and r.role == "mixture")
        d = ProcessDialog(self.win, mixes)
        d.editor.set_steps([{"op": "divide", "params": {"reference": self.named("CAF 10")}},
                            {"op": "derivative", "params": {"order": 1, "delta_lambda": 4.0}}])
        d._preview()
        self.s.shot(d, "pipeline", "Processing pipelines with live preview",
                    "chain smoothing, baseline, derivatives, ratio spectra and spectrum "
                    "resolution; results are new derived spectra — raw data is never changed "
                    "and every result can be recomputed and verified.",
                    "Process → Processing pipeline…")

    # 5
    def views(self):
        select(self.win, self.ids(lambda r: r.kind == "raw" and r.role == "mixture"))
        self.win.view_cb.setCurrentText("Stacked")
        self.s.shot(self.win, "stacked", "Stacked, difference and normalized views",
                    "compare many spectra at a glance; difference view shows exactly how each "
                    "spectrum departs from a reference.", "View selector above the plot")
        self.win.view_cb.setCurrentText("Overlay")

    # 6–7
    def optimizer(self):
        from spectro.ui.dialog_optimizer import OptimizerDialog
        d = OptimizerDialog(self.win)
        for i in range(d.comps.count()):
            d.comps.item(i).setCheckState(Qt.Checked if d.comps.item(i).text() in ("PAR", "CAF")
                                          else Qt.Unchecked)
        d._refresh_inputs()
        d._run()
        uni = next(i for i, c in enumerate(d.cands) if c.measurement)
        d.table.selectRow(uni)
        self.s.shot(d, "optimizer_binary", "Method optimizer — binary mixture",
                    "ranks every processing strategy (zero order, derivatives, dual wavelength, "
                    "ratio methods, subtraction methods, amplitude centering, absorption factor, "
                    "Vierordt, bivariate, CLS, PLS) by predicted interference, noise and ±λ "
                    "robustness, verified on simulated and laboratory mixtures — finds the best "
                    "method in seconds instead of weeks.",
                    "Tools → Method optimizer")
        for i in range(d.comps.count()):
            d.comps.item(i).setCheckState(Qt.Checked)
        d._refresh_inputs()
        d._run()
        d.show_comp.setCurrentText("CAF")
        ac = next(i for i, c in enumerate(d.cands) if c.family == "amplitude_centering"
                  and not c.error)
        d.table.selectRow(ac)
        self.s.shot(d, "optimizer_ternary", "Method optimizer — ternary mixture",
                    "for three overlapping drugs it shows which strategies still work and which "
                    "fail, with the expected error of each; selecting an amplitude-centering row "
                    "plots the ratio spectra with the wavelengths it chose.",
                    "Tools → Method optimizer (3 compounds) → select a row")
        self.opt_ternary = d

    # 8
    def univariate(self):
        from spectro.ui.dialogs_methods import UnivariateDialog
        d = UnivariateDialog(self.win)
        d.resize(1450, 880)
        d.compound.setCurrentText("PAR")
        d.template.setCurrentText("Ratio difference (RD)")
        st = d.pipe.get_steps()
        st[0]["params"]["reference"] = self.named("CAF 10")
        d.pipe.set_steps(st)
        d.meas.form.set_value("w1", 243.0)
        d.meas.form.set_value("w2", 265.0)
        d._preview()
        self.s.shot(d, "univariate_setup", "Univariate methods — 29 templates in 5 families",
                    "pick a published method from the list grouped by family (zero order, "
                    "derivative, ratio-derivative, ratio-amplitude, spectrum resolution), see the "
                    "processed spectra and drag the λ markers to the best position.",
                    "Methods → Univariate calibration")
        d._calibrate()
        self.s.shot(d, "univariate_calibration", "Calibration with full ICH statistics",
                    "slope/intercept with SD and 95 % CI, r, Sy/x, LOD/LOQ and residual plot "
                    "are computed automatically.", "Calibrate")
        tabs = self.ids(lambda r: r.kind == "raw" and (r.role == "mixture" or "Panadol" in r.name))
        check_only(d.test, tabs)
        d._predict()
        self.s.shot(d, "univariate_results", "Assay of mixtures and tablets",
                    "found, taken and % recovery (or % label claim) with mean, SD and RSD — "
                    "ready to paste into a paper or export to Excel.", "Determine")
        return d

    # 9–10
    def studies(self, d):
        from spectro.core.spectrum import Spectrum
        from spectro.ui.dialogs_methods import RobustnessDialog
        tid = self.p.trials()[0]["id"]
        tab = self.p.spectrum(self.named("Panadol Extra tablet 1 (label claim)"))
        par10 = self.p.spectrum(self.named("PAR 10 ug/mL"))
        spikes = []
        rng = np.random.default_rng(7)  # measurement noise + pipetting error of each solution
        for i, a in enumerate([0, 0, 4, 8, 12]):
            y = (tab.y * rng.normal(1, 0.002) + a / 10 * np.interp(tab.x, par10.x, par10.y)
                 * rng.normal(1, 0.004) + rng.normal(0, 0.0004, tab.x.size)
                 + rng.normal(0, 0.001))
            s = Spectrum(tab.x, y,
                         name=f"Tablet 1 + {a} µg/mL PAR (simulated spike {i + 1})",
                         concentrations={"PAR": float(a)})
            spikes.append(self.p.add_spectrum(s, tid, role="sample", note="simulated spike"))
        d.test.populate([r for r in self.p.records() if r.kind == "raw"], set(spikes))
        d._std_addition()
        self.s.shot(d, "standard_addition", "Standard addition inside the method",
                    "checks accuracy in the real matrix: recovery of each spike and the "
                    "extrapolated content, with the same calibrated method.",
                    "Standard addition… (spiked samples)")
        mixes = self.ids(lambda r: r.kind == "raw" and r.role == "mixture")
        rob = RobustnessDialog(d, d.method, self.p.spectra(d.cal_ids), self.p.spectra(mixes))
        rob.resize(1050, 640)
        rob._run()
        self.s.shot(rob, "robustness", "Robustness study in one click",
                    "each parameter (λ, Δλ, plateau, window…) is varied by ±Δ, re-calibrated and "
                    "re-assayed; the % deviation shows whether the method is robust (ICH Q2).",
                    "Robustness…")

    # 11
    def equations(self):
        from spectro.ui.dialogs_methods import EquationsDialog
        from spectro.ui.widgets import fill_table
        d = EquationsDialog(self.win)
        d.resize(1400, 820)
        for i in range(d.comps.count()):
            d.comps.item(i).setCheckState(Qt.Checked if d.comps.item(i).text() in ("PAR", "CAF")
                                          else Qt.Unchecked)
        fill_table(d.signals, ["Kind (amplitude/area)", "λ1 (nm)", "λ2 (nm, area only)"],
                   [["amplitude", "243", ""], ["amplitude", "273", ""]], editable=True)
        std = self.ids(lambda r: r.kind == "raw" and r.role in ("standard", "divisor")
                       and (r.name.startswith("PAR") or r.name.startswith("CAF")))
        check_only(d.cal, std)
        check_only(d.test, self.ids(lambda r: r.kind == "raw" and (r.role == "mixture" or
                                                                  "Panadol" in r.name)))
        d._fit()
        d._predict()
        self.s.shot(d, "vierordt", "Simultaneous equations (Vierordt / bivariate / AUC)",
                    "classic multi-wavelength methods with the coefficient matrix, its condition "
                    "number and recoveries for every compound.", "Methods → Equation methods")

    # 11b
    def special(self):
        from spectro.core import univariate as uv
        from spectro.ui.dialogs_methods import SpecialDialog
        d = SpecialDialog(self.win)
        d.resize(1300, 820)
        d.q_x.setCurrentText("PAR")
        d.q_y.setCurrentText("CAF")
        par = [r for r in self.p.records() if r.kind == "raw" and r.role == "standard"
               and r.concentrations.get("PAR") and not r.concentrations.get("CAF")]
        caf = [r for r in self.p.records() if r.kind == "raw" and r.role == "standard"
               and r.concentrations.get("CAF") and not r.concentrations.get("PAR")]
        a, b = self.p.spectrum(par[3].id), self.p.spectrum(caf[3].id)
        iso = [w for w in uv.isoabsorptive_points(a, b, a.concentrations["PAR"],
                                                  b.concentrations["CAF"]) if 225 < w < 300]
        d.q_iso.setValue(round(iso[0], 1))
        d.q_w2.setValue(243.0)
        check_only(d.q_xs, [r.id for r in par])
        check_only(d.q_ys, [r.id for r in caf])
        check_only(d.q_mix, self.ids(lambda r: r.kind == "raw" and r.role == "mixture"
                                     and "PAR" in r.concentrations and "ASA" not in
                                     r.concentrations))
        d._run_q()
        self.s.shot(d, "two_signal", "Binary two-signal methods (Q-analysis, AS, AAS, AM, IAM, "
                    "HPSAM)", "methods that need several signals at once, grouped by family; "
                    "the isoabsorptive point is found from the standards with one click.",
                    "Methods → Binary two-signal methods")

    # 11c
    def progressive(self):
        """Apply the amplitude-centering method proposed by the optimizer."""
        from PySide6.QtWidgets import QTableWidgetItem
        from spectro.ui.dialogs_methods import ProgressiveDialog
        opt = getattr(self, "opt_ternary", None)
        if opt is None:
            self.optimizer()
            opt = self.opt_ternary
        best = min((c for comp in opt.inp.compounds for c in opt.result["ranked"][comp]
                    if c.family == "amplitude_centering" and not c.error),
                   key=lambda c: c.score)
        m = best.model
        z = m["divisor_compound"]
        d = ProgressiveDialog(self.win)
        d.resize(1300, 1000)
        for i in range(d.ac_comps.count()):
            it = d.ac_comps.item(i)
            it.setCheckState(Qt.Checked if it.text() in m["compounds"] else Qt.Unchecked)
        d.ac_div.setCurrentIndex(d.ac_div.findData(opt.div_boxes[z].currentData()))
        d.ac_divc.setCurrentText(z)
        d.ac_w.setValue(m["wavelength"])
        d.ac_plateau.setChecked(bool(m["plateau"]))
        for i, (c, df) in enumerate(m["differences"].items()):
            for j, v in enumerate((c, f"{df['w1']:.1f}", f"{df['w2']:.1f}",
                                   df.get("factor_from") or "")):
                d.ac_diff.setItem(i, j, QTableWidgetItem(v))
        d.ac_sub.setCurrentText(m["subtract"])
        check_only(d.ac_std, [i for c in m["compounds"] for i in opt.std_ids[c]])
        check_only(d.ac_mix, self.ids(lambda r: r.kind == "raw" and r.role == "validation"))
        d._run_ac()
        self.s.shot(d, "progressive", "Progressive resolution: amplitude centering",
                    "AAC / MACM / RIDSS / CV-AD resolve all three drugs from ONE ratio spectrum "
                    "at ONE wavelength; here with the settings the optimizer proposed. Saved "
                    "like any method and applied to new samples.",
                    "Methods → Progressive resolution")

    # 12
    def chemometrics(self):
        from spectro.ui.dialogs_methods import ChemometricsDialog
        d = ChemometricsDialog(self.win)
        d.resize(1450, 900)
        d.ranges.setText("215-310")
        check_only(d.test, self.ids(lambda r: r.kind == "raw" and (r.role == "validation" or
                                                                  "Excedrin" in r.name)))
        d.cv.setCurrentText("venetian")
        d._cv()
        self.s.shot(d, "chemometrics_cv", "Chemometrics: cross-validation",
                    "CLS, ILS, PCR, PLS, MCR-ALS, ANN and SVR with RMSECV curves and automatic "
                    "choice of the number of components.", "Methods → Chemometrics")
        d._fit()
        d.tabs.setCurrentIndex(1)
        self.s.shot(d, "chemometrics_prediction", "Chemometrics: prediction of validation "
                    "mixtures and tablets", "predicted-vs-actual plot, RMSEP and recoveries per "
                    "compound.", "Fit + predict")
        d.tabs.setCurrentIndex(3)
        self.s.shot(d, "chemometrics_outliers", "Outlier detection with T² / Q limits",
                    "95/99 % limits flag unusual calibration or sample spectra; one click "
                    "excludes flagged spectra and refits. Fitted models are saved and exportable.",
                    "Outliers tab")

    # 13
    def validation(self):
        from PySide6.QtWidgets import QTableWidgetItem
        from spectro.ui.dialogs_tools import ValidationDialog
        d = ValidationDialog(self.win)
        t = d.inputs["Compare methods"]
        rd = [99.8, 100.4, 99.2, 100.9, 99.6, 100.3]
        ref = [100.2, 99.7, 100.6, 99.4, 100.1, 99.9]
        for i, (a, b) in enumerate(zip(rd, ref)):
            t.setItem(i, 0, QTableWidgetItem(str(a)))
            t.setItem(i, 1, QTableWidgetItem(str(b)))
        d.tabs.setCurrentIndex(3)
        d._calc("Compare methods")
        self.s.shot(d, "validation", "ICH Q2(R2) validation statistics",
                    "linearity, LOD/LOQ, accuracy, precision/ANOVA, Student's t, F-test and the "
                    "interval hypothesis test — no spreadsheet formulas to check.",
                    "Tools → Validation statistics")
        t = d.inputs["Compare (mean, SD, n)"]
        rows = [("Reported HPLC", 100.63, 0.726, 5), ("AAS", 100.60, 0.821, 5),
                ("IDW", 99.80, 1.067, 5), ("RD", 100.01, 0.607, 5), ("DR1", 99.95, 0.735, 5),
                ("MCR", 99.73, 0.889, 5)]
        for i, r in enumerate(rows):
            for j, v in enumerate(r):
                t.setItem(i, j, QTableWidgetItem(str(v)))
        d.tabs.setCurrentIndex(list(d.inputs).index("Compare (mean, SD, n)"))
        d._calc("Compare (mean, SD, n)")
        self.s.shot(d, "validation_summary", "Compare with a reported method from mean, SD, n",
                    "t, F (one-tailed table value, as in the literature) and one-way ANOVA "
                    "straight from published summary values — here Eissa 2018, Table 4 "
                    "(reproduces the paper's t, F and ANOVA).",
                    "Tools → Validation statistics → Compare (mean, SD, n)")

    # 14
    def design(self):
        from spectro.ui.dialogs_tools import DesignDialog
        d = DesignDialog(self.win)
        d._gen()
        self.s.shot(d, "design", "Calibration design for multivariate models",
                    "Brereton 5-level multifactor design with the volume of each stock solution "
                    "to pipette — balanced, uncorrelated training mixtures.",
                    "Tools → Calibration design")

    # 15
    def greenness(self):
        from spectro.ui.dialogs_tools import GreennessDialog
        d = GreennessDialog(self.win)
        for i, v in enumerate([0.9, 0.8, 0.3, 0.7, 0.6, 1.0, 0.7, 0.9, 0.8, 0.5, 0.6, 0.8]):
            d.a_scores[i].setValue(v)
        self.s.shot(d, "greenness", "Greenness assessment (AGREE, Eco-Scale, GAPI)",
                    "the greenness metrics journals ask for, with the pictogram, in the same "
                    "tool as the analysis.", "Tools → Greenness assessment")

    # 16
    def figure(self):
        from spectro.ui.figure import FigureDialog
        select(self.win, self.ids(lambda r: r.kind == "raw" and r.role == "mixture"))
        d = FigureDialog(self.win.plot, self.win)
        d.bw.setChecked(True)
        d._update()
        self.s.shot(d, "figure", "Publication-quality figures",
                    "any plot → journal-ready TIFF/PNG (300–1200 dpi) or vector SVG/PDF/EPS, "
                    "size in mm, fonts, black-and-white mode, with live preview.",
                    "Right-click a plot → Export publication figure")

    # 17
    def results(self):
        from spectro.ui.dialogs_methods import SavedDialog
        d = SavedDialog(self.win)
        d.findChild(__import__("PySide6.QtWidgets", fromlist=["QTabWidget"]).QTabWidget) \
            .setCurrentIndex(1)
        row = next(i for i, r in enumerate(d.res) if r["name"].startswith("PLS2"))
        d.rtable.selectRow(row)
        d._show_result()
        self.s.shot(d, "results", "Saved methods and results, Excel export",
                    "every calibration and assay is stored with its method; results export to "
                    "Excel (one sheet each) and methods to portable .spmodel files.",
                    "Methods → Saved methods & results")

    # 17b
    def editing(self):
        from spectro.ui.dialogs_data import ProcessDialog
        from spectro.ui.dialogs_methods import ResultEditDialog
        der = self.ids(lambda r: r.kind == "derived" and r.pipeline
                       and r.pipeline[0]["op"] == "derivative")
        if not der:
            der = self.ids(lambda r: r.kind == "derived")
        d = ProcessDialog(self.win, der[:6], edit=True)
        self.s.shot(d, "edit_processing", "Edit a processing chain after the fact",
                    "change any step (Δλ, smoothing window, divisor…) of processed spectra; "
                    "they are recomputed from their parents, everything built on them is "
                    "rebuilt, and the old versions stay archived with the reason in the audit "
                    "trail.",
                    "Select processed spectra → Process → Edit processing of selected spectra… "
                    "(or Lineage tab → Edit processing…)")
        res = next(r for r in self.p.results() if isinstance(r["data"].get("found"), list)
                   and r["data"].get("ids"))
        e = ResultEditDialog(self.win, res["id"])
        e.table.item(0, 0).setCheckState(Qt.Unchecked)
        e.excl_note.setText("bubble in the cuvette — re-measured")
        e.notes.setPlainText("Second analyst checked the dilutions.")
        self.s.shot(e, "edit_result", "Edit a saved result",
                    "rename, add notes, exclude a spectrum from the statistics (kept and "
                    "marked), or recalculate with the current method and corrected "
                    "concentrations — saved as a new version, never overwritten.",
                    "Methods → Saved methods & results → Results → Edit…")

    # 18
    def report(self):
        from spectro.ui.report import build_html
        v = QTextBrowser()
        v.resize(1100, 900)
        v.setHtml(build_html(self.p, self.p.trials()[0]["id"]))
        self.s.shot(v, "report", "Trial report with audit trail",
                    "one click produces a PDF/HTML report: spectra, processing lineage, methods, "
                    "results, integrity check and the audit trail.",
                    "File → Trial report")


WORKFLOWS = ["import_any_instrument", "organize", "audit", "pipeline", "views", "optimizer",
             "univariate", "equations", "special", "progressive", "chemometrics", "validation",
             "design", "greenness", "figure", "results", "editing", "report"]


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--out", default=str(ROOT / "docs" / "workflows"))
    ap.add_argument("--only", default="", help="comma-separated workflow names")
    args = ap.parse_args(argv)
    app = QApplication.instance() or QApplication(sys.argv[:1])
    app.setStyle("Fusion")
    shooter = Shooter(Path(args.out), app)
    only = [w for w in args.only.split(",") if w]
    failures = []
    with tempfile.TemporaryDirectory() as tmp:
        demo = Demo(shooter, Path(tmp))
        uni = None
        for name in WORKFLOWS:
            if only and name not in only and not (name == "univariate" and "studies" in only):
                continue
            print(f"{name}…")
            try:
                res = getattr(demo, name)()
                if name == "univariate":
                    uni = res
                    if not only or "studies" in only:
                        demo.studies(uni)
            except Exception:
                failures.append(name)
                traceback.print_exc()
        demo.win.close_project()
    shooter.write_index()
    print(f"\n{len(shooter.entries)} screenshots + index.html + README.md in {args.out}")
    if failures:
        print("FAILED:", ", ".join(failures))
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
